CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  type ENUM('folder', 'note') NOT NULL,
  name VARCHAR(160) NOT NULL,
  directory_path VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_items_user_directory (user_id, directory_path),
  INDEX idx_items_user_type (user_id, type),
  CONSTRAINT fk_items_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notes (
  item_id BIGINT UNSIGNED PRIMARY KEY,
  raw_text MEDIUMTEXT NOT NULL,
  ai_summary MEDIUMTEXT NULL,
  language VARCHAR(80) NOT NULL DEFAULT 'English',
  duration_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  source_type ENUM('recording', 'generated_summary', 'generated_practice_exam', 'slide_pdf', 'generated_flashcards') NOT NULL DEFAULT 'recording',
  generated_from_count INT UNSIGNED NULL,
  pdf_file_path VARCHAR(600) NULL DEFAULT NULL,
  youtube_source_url VARCHAR(500) NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_notes_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);
